# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'playingWithCocoaPods' do
	pod 'NSDate+TimeAgo', '~> 1.0'
	pod 'MarqueeLabel', '~> 2.7'
end

