# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
 use_frameworks!

target 'testingAdvLecture' do

end

target 'testingAdvLectureTests' do
  pod 'Quick', '~> 0.9.0'
  pod 'Nimble', '~> 3.2.0'
end

